language: node_js
node_js:
  - 10.13.0
  - 8.13.0
  - 6.14.4

cache: yarn
sudo: false

script:
  - yarn lint
  - yarn format:check
  - yarn test:coverage --ci --maxWorkers=2 --verbose

after_success: yarn coveralls
