language: node_js
node_js:
  - 8.11.4
  - lts/boron
  - 6.14.2

cache: yarn
sudo: false

script:
  - yarn lint
  - yarn format:check
  - yarn test:coverage --ci --maxWorkers=2 --verbose

after_success: yarn coveralls
